'use strict'

/**
 * Standalone native iOS builds via Capacitor — the "generate" half of native mode.
 *
 * A product's standalone iOS app is a Capacitor WKWebView wrapper living in
 * `<repo>/mobile/` (mirrors the Electron `<repo>/desktop/` wrapper, targeting iOS
 * instead of the desktop). This module owns that project's lifecycle:
 *
 *   initProject(p)  -> scaffold <repo>/mobile/ (package.json + capacitor.config + ios/)
 *   syncProject(p)  -> copy the latest web assets into the native project (`cap sync`)
 *   buildApp(p)     -> xcodebuild a Simulator .app and return its path + bundle id
 *
 * The built .app bundles the product's REAL shippable web assets (webDir points
 * straight at the product's webRoot — the same bytes the static server serves),
 * so driving it in the Simulator tests the actual standalone artifact, not a
 * dev-server proxy. Simulator builds need no code signing (CODE_SIGNING_ALLOWED=NO).
 *
 * Design rules honored: reproducible (init writes real config, no hand-steps),
 * one attempt per command with the real stderr surfaced, tool-level incrementality
 * (xcodebuild/cap reuse their own caches) rather than bespoke staleness logic.
 */

const fs = require('node:fs')
const path = require('node:path')
const { spawn, execFileSync } = require('node:child_process')
const server = require('./server')

// ── Pure helpers (unit-tested; no side effects) ─────────────────────────────

/** The Capacitor project directory for a product: <repo>/mobile/. */
function mobileDir(product) {
    return path.join(product.repoPath, 'mobile')
}

/** Capacitor's iOS Xcode project lives under mobile/ios/App/. */
function iosDir(product) {
    return path.join(mobileDir(product), 'ios')
}

function workspacePath(product) {
    return path.join(iosDir(product), 'App', 'App.xcworkspace')
}

/** derivedData / build output root (kept inside mobile/ so it's git-ignorable). */
function buildDir(product) {
    return path.join(mobileDir(product), 'build')
}

/**
 * The compiled Simulator app bundle. Capacitor names the Xcode target "App",
 * so the product is always App.app regardless of the display appName.
 */
function appPath(product) {
    return path.join(buildDir(product), 'Build', 'Products', 'Debug-iphonesimulator', 'App.app')
}

function bundleId(product) {
    return product.native.appId
}

/** The app's Info.plist (for native permission strings). */
function infoPlistPath(product) {
    return path.join(iosDir(product), 'App', 'App', 'Info.plist')
}

/** The synced web bundle's entry HTML (`cap sync` copies webDir → here). */
function syncedIndexPath(product) {
    return path.join(iosDir(product), 'App', 'App', 'public', 'index.html')
}

/**
 * `.gitignore` for <repo>/mobile/. The native PROJECT (xcodeproj/workspace/Podfile)
 * and config ARE meant to be tracked; this keeps the heavy regenerated output out
 * of the product repo: xcodebuild's derivedData (build/), npm deps, and the web
 * assets `cap sync` copies in (a duplicate of the product's web root).
 */
function gitignoreBody() {
    return [
        '# Capacitor iOS wrapper — generated output (regenerated by npm install / cap sync / xcodebuild).',
        '# The native project (ios/App/*.xcodeproj, *.xcworkspace, Podfile) + config are tracked.',
        'build/',
        'node_modules/',
        'ios/App/App/public/',
        '',
    ].join('\n')
}

/**
 * The capacitor.config.json contents for a product. webDir points at the
 * product's real webRoot, relative to mobile/ — so the build bundles the exact
 * shippable assets. contentInset:'always' keeps content clear of the status bar.
 */
function capacitorConfig(product) {
    return {
        appId: product.native.appId,
        appName: product.native.appName,
        webDir: path.posix.join('..', product.webRoot),
        ios: { contentInset: 'always' },
    }
}

/** package.json for the Capacitor wrapper (mirrors <repo>/desktop/'s role). */
function mobilePackageJson(product) {
    return {
        name: `${product.key}-mobile`,
        version: '1.0.0',
        private: true,
        description: `${product.native.appName} iOS build (Capacitor WKWebView wrapper). Mirrors the desktop/ Electron wrapper, targeting iOS.`,
        scripts: { sync: 'cap sync ios', open: 'cap open ios' },
        dependencies: { '@capacitor/core': '^7.0.0', '@capacitor/ios': '^7.0.0' },
        devDependencies: { '@capacitor/cli': '^7.0.0' },
    }
}

/** xcodebuild argument vector for an unsigned Simulator build. */
function xcodebuildArgs(product, { clean = false } = {}) {
    const args = [
        '-workspace', workspacePath(product),
        '-scheme', 'App',
        '-configuration', 'Debug',
        '-sdk', 'iphonesimulator',
        '-derivedDataPath', buildDir(product),
        'CODE_SIGNING_ALLOWED=NO',
    ]
    if (clean) args.unshift('clean')
    return args
}

function isInitialized(product) {
    return (
        fs.existsSync(path.join(mobileDir(product), 'capacitor.config.json')) &&
        fs.existsSync(workspacePath(product))
    )
}

// ── Command runner with a heartbeat (no silent multi-minute hangs) ──────────

function runStreaming(cmd, args, { cwd, env, timeout = 1_200_000, log = () => {}, label } = {}) {
    return new Promise((resolve, reject) => {
        const child = spawn(cmd, args, { cwd, env: env || process.env, stdio: ['ignore', 'pipe', 'pipe'] })
        const tail = []
        const push = (d) => {
            tail.push(d.toString())
            if (tail.length > 200) tail.shift()
        }
        child.stdout.on('data', push)
        child.stderr.on('data', push)

        const started = Date.now()
        const hb = setInterval(() => {
            log(`      … ${label || cmd} still running (${Math.round((Date.now() - started) / 1000)}s)`)
        }, 30000)
        const killer = setTimeout(() => {
            child.kill('SIGKILL')
        }, timeout)

        const done = (fn, arg) => {
            clearInterval(hb)
            clearTimeout(killer)
            fn(arg)
        }
        child.on('error', (e) => done(reject, new Error(`${cmd} failed to spawn: ${e.message}`)))
        child.on('close', (code) => {
            if (code === 0) return done(resolve, { stdout: tail.join('') })
            const out = tail.join('').slice(-3000)
            done(reject, new Error(`${label || cmd} exited ${code}:\n${out}`))
        })
    })
}

/**
 * Camera apps (photobox/glitcher) call getUserMedia. A native WKWebView needs
 * NSCameraUsageDescription in Info.plist or the request is blocked outright (and
 * on some iOS versions the app is terminated for touching the camera without it) —
 * a shipping camera app requires it regardless. With it, the Simulator (no camera)
 * rejects cleanly with NotFound/NotReadable, which is the graceful-degradation path
 * the specs assert. Idempotent (Add if missing, else Set). PlistBuddy is bundled
 * with macOS. No-op for non-camera products.
 */
function ensureNativePermissions(product, { log = () => {} } = {}) {
    if (!product.capabilities || !product.capabilities.camera) return
    const plist = infoPlistPath(product)
    if (!fs.existsSync(plist)) return
    const key = 'NSCameraUsageDescription'
    const desc = `${product.native.appName} uses the camera for its photo/video tools.`
    const pb = (cmd) => {
        try {
            execFileSync('/usr/libexec/PlistBuddy', ['-c', cmd, plist], { stdio: 'pipe' })
            return true
        } catch (_) {
            return false
        }
    }
    if (!pb(`Add :${key} string ${desc}`)) pb(`Set :${key} ${desc}`)
    log(`    Info.plist: ${key} ensured for ${product.key}`)
}

/**
 * Inject the instrumentation shim as the FIRST <script> of the native build's
 * bundled index.html (which `cap sync` just copied in). Native apps load their own
 * bundled assets, so the HTTP server's load-time injection never runs for them;
 * doing it here gives native mode the SAME first-script capture as web mode
 * (catching load-time errors the post-load bridge install would miss). The shim is
 * observation-only and the file is gitignored synced output, so nothing ships.
 */
function injectTrapIntoBundle(product, { log = () => {} } = {}) {
    const idx = syncedIndexPath(product)
    if (!fs.existsSync(idx)) {
        log(`    ⚠ ${product.key}: no synced index.html (${idx}); native trap installs post-load only`)
        return false
    }
    const html = fs.readFileSync(idx, 'utf8')
    if (html.includes('data-ios-harness')) return true
    fs.writeFileSync(idx, server.injectTrap(html))
    log(`    injected instrumentation shim into ${product.key}'s bundled index.html (first-script)`)
    return true
}

// ── Lifecycle (side-effecting) ──────────────────────────────────────────────

/**
 * Scaffold <repo>/mobile/ reproducibly: write package.json + capacitor.config.json,
 * `npm install`, then `npx cap add ios` (which also runs `pod install`). Idempotent —
 * a no-op when the project already has an ios/ workspace, unless force is set.
 */
async function initProject(product, { log = () => {}, force = false } = {}) {
    if (!product.native) throw new Error(`${product.key} has no native build config (products.js: native:{appId,appName})`)
    const dir = mobileDir(product)
    fs.mkdirSync(dir, { recursive: true })
    // Always (idempotently) ensure the wrapper's .gitignore so generated output never
    // lands in the product repo — including projects scaffolded before this existed.
    fs.writeFileSync(path.join(dir, '.gitignore'), gitignoreBody())

    if (isInitialized(product) && !force) {
        log(`    mobile/ already initialized for ${product.key}`)
        ensureNativePermissions(product, { log })
        return { dir }
    }
    fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify(mobilePackageJson(product), null, 2) + '\n')
    fs.writeFileSync(path.join(dir, 'capacitor.config.json'), JSON.stringify(capacitorConfig(product), null, 4) + '\n')

    // webDir must exist before `cap add ios` (Capacitor validates it).
    if (!fs.existsSync(product.webRootPath)) {
        throw new Error(`${product.key} webRoot missing: ${product.webRootPath} — nothing to bundle`)
    }

    log(`    npm install (capacitor) for ${product.key}…`)
    await runStreaming('npm', ['install'], { cwd: dir, log, label: 'npm install' })
    if (!fs.existsSync(iosDir(product))) {
        log(`    npx cap add ios for ${product.key} (pod install — first run is slow)…`)
        await runStreaming('npx', ['cap', 'add', 'ios'], { cwd: dir, log, label: 'cap add ios' })
    }
    ensureNativePermissions(product, { log })
    return { dir }
}

/** Copy the latest web assets into the native project (`cap sync ios`). */
async function syncProject(product, { log = () => {} } = {}) {
    const dir = mobileDir(product)
    if (!fs.existsSync(path.join(dir, 'node_modules', '@capacitor', 'cli'))) {
        log(`    npm install (capacitor) for ${product.key}…`)
        await runStreaming('npm', ['install'], { cwd: dir, log, label: 'npm install' })
    }
    // `cap sync` runs `pod install`, whose post-install `xcodebuild clean` aborts
    // if a default-location ios/App/build/ exists (e.g. left by opening the
    // project in Xcode). We force build output to mobile/build/ via derivedDataPath,
    // so this project-relative dir is always disposable cruft — clear it.
    fs.rmSync(path.join(iosDir(product), 'App', 'build'), { recursive: true, force: true })
    log(`    cap sync ios (${product.key})…`)
    await runStreaming('npx', ['cap', 'sync', 'ios'], { cwd: dir, log, label: 'cap sync ios' })
}

/**
 * Build the standalone Simulator .app. Inits the project if needed, syncs the
 * latest web assets, then xcodebuilds (unsigned). Returns { appPath, bundleId,
 * appName }. Throws with the xcodebuild tail if the .app is not produced.
 */
async function buildApp(product, { log = () => {}, clean = false } = {}) {
    if (!product.native) throw new Error(`${product.key} has no native build config`)
    if (!isInitialized(product)) await initProject(product, { log })
    await syncProject(product, { log })
    // First-script trap parity with web mode (cap sync just refreshed the bundle).
    injectTrapIntoBundle(product, { log })

    log(`    xcodebuild ${product.key} (Debug / iphonesimulator, unsigned — a few minutes)…`)
    await runStreaming('xcodebuild', xcodebuildArgs(product, { clean }), {
        cwd: mobileDir(product),
        log,
        label: 'xcodebuild',
    })

    const out = appPath(product)
    if (!fs.existsSync(out)) {
        throw new Error(`xcodebuild reported success but ${out} is missing — build layout changed?`)
    }
    return { appPath: out, bundleId: bundleId(product), appName: product.native.appName }
}

module.exports = {
    // pure
    mobileDir,
    iosDir,
    workspacePath,
    buildDir,
    appPath,
    bundleId,
    infoPlistPath,
    syncedIndexPath,
    gitignoreBody,
    capacitorConfig,
    mobilePackageJson,
    xcodebuildArgs,
    isInitialized,
    // lifecycle
    initProject,
    syncProject,
    buildApp,
    runStreaming,
}
